package classicondivise;


public enum ComunicazioneController {
    PASSA_TURNO,
    ELEGGERE_CONSIGLIERE,
    ACQUISTARE_TESSERA_PERMESSO_COSTRUZIONE,
    COSTRUIRE_EMPORIO_CON_TESSERA_PERMESSO_COSTRUZIONE,
    COSTRUIRE_EMPORIO_CON_AIUTO_RE,
    INGAGGIARE_AIUTANTE,
    CAMBIARE_TESSERE_PERMESSO_COSTRUZIONE,
    MANDARE_AIUTANTE_ELEGGERE_CONSIGLIERE,
    COMPIERE_AZIONE_PRINCIPALE_AGGIUNTIVA,
<<<<<<< HEAD
    VENDI,
    COMPRA;
=======
    LOGOUT;
>>>>>>> a352b7fd2e37d574602694014116efab418f6d3c
}
