package classicondivise;

public enum ComunicazioneView {
    SET_ID_GIOCATORE,
    GET_ID_GIOCATORE,
    SCEGLI_MAPPA,
    INIZIA_A_GIOCARE,
    ERRORE_DI_CONNESSIONE,
    UPDATE_PUNTI_VITTORIA_GIOCATORE,
    UPDATE_BALCONE,
    UPDATE_MONETE,
    UPDATE_CARTE_POLITICA_AVVERSARI,
    UPDATE_CARTE_POLITICA_PROPRIE,
    UPDATE_CARTE_PERMESSO_REGIONE,
    UPDATE_CARTE_PERMESSO_GIOCATORE,
    UPDATE_AIUTANTI,
    UPDATE_RISERVA_AIUTANTI,
    UPDATE_RISERVA_CONSIGLIERI,
    UPDATE_PERCORSO_NOBILTA,
    UPDATE_BONUS_PERCORSO_NOBILTA,
    UPDATE_EMPORI_CITTA,
    UPDATE_BONUS_CITTA,
    UPDATE_EMPORI_DISPONIBILI_GIOCATORE,
    UPDATE_POSIZIONE_RE,
    ESEGUI_TURNO,
    FINE_TURNO,
    MOSTRA_MESSAGGIO;
}
